# This is a configuration file for a machine learning experiment using the MoEGCN method on the CiteSeer dataset.
  # fix parameters
  dataset: wikics
  method: MoEGCN
  runs: 1
  seed: 42
  device: 0
  cpu: False
  debug: True
  domain: degree
  shift: concept
  ood_homophily_split: True
  TTT: True
  trail: 0
  log_steps: 10
  display_step: 10
  adam: False
  SGD: False
  rand_split: False
  train_prop: 0.6
  valid_prop: 0.2


  # optuna parameters in pre-train phase
  ## model related
  hidden_channels: 256
  num_layers: 3
  dropout: 0.2
  max_node: 10
  mlp_layer: 1
  ## optimzer related
  lr: 0.001
  weight_decay: 5e-4
  gating_lr: 0.0001
  gating_weight_decay: 5e-4
  epochs: 50
  ## align loss related
  align_loss_weight: 0.5
  num_clusters: 5
  alpha: 10
  max_iter: 5
  use_match_matrix: True

  # optuna parameters in test-time training phase
  ## optimzer related
  ttt_lr: 0.0001
  ttt_weight_decay: 0.5
  ttt_epochs: 60
  ## align loss related
  ttt_num_clusters: 5
  ttt_alpha: 10
  ttt_max_iter: 5
  ttt_use_match_matrix: True

  # Others
  norm: bn
  num_mlp_layers: 1
  no_bn: False
  gpr_alpha: 0.1
  gcn2_alpha: 0.1
  theta: 0.5
  num_experts: 4
  k: 1
  coef: 1e-2

